#index:
#    path: /
#    controller: App\Controller\DefaultController::index

post_create:
  path: /create-post
  controller:
    App\Infrastructure\Controller\CreatePostController::create
  methods: [POST]

get-posts:
  path: /get-posts
  controller:
    App\Infrastructure\Controller\GetPostsController::getPosts
  methods: [GET]

edit-post:
  path: /edit-post
  controller:
    App\Infrastructure\Controller\EditPostController::editPost
  methods: [PATCH]


